### ISSUE TITLE
Not really an issue, but nice work with libLink!

### ISSUE THREAD

**Issue by mgibbs189** [leongersen/libLink#1]
Really makes things easier compared to the old serialization approach! :+1:

**Comment by leongersen** [comment]
Hi Matt,

Thanks for your response! You've been really involved in my projects, which has made working on them a lot more fun :)

Splitting the serialization feature into its own module allowed for a large simplification of the source code, so I think it was well worth it. Examples seem simpler too. Another mayor benefit is that both modules are now independently tested.
